//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoLWay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class builds
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public builds()
        {
            this.item = new HashSet<item>();
            this.rune = new HashSet<rune>();
        }
    
        public int id { get; set; }
        public string userId { get; set; }
        public int championId { get; set; }
        public int masteryId { get; set; }
        public System.DateTime modificationDate { get; set; }
        public string notes { get; set; }
    
        public virtual aspnetusers aspnetusers { get; set; }
        public virtual champion champion { get; set; }
        public virtual mastery mastery { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<item> item { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rune> rune { get; set; }
    }
}
