//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoLWay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class build
    {
        public int id { get; set; }
        public string userId { get; set; }
        public int championId { get; set; }
        public int masteryId { get; set; }
        public System.DateTime modificationDate { get; set; }
        public string notes { get; set; }
        public string runes { get; set; }
        public string items { get; set; }
    
        public virtual aspnetusers aspnetusers { get; set; }
        public virtual champion champion { get; set; }
        public virtual mastery mastery { get; set; }
    }
}
