//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoLWay.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class lolwayEntities : DbContext
    {
        public lolwayEntities()
            : base("name=lolwayEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<build> build { get; set; }
        public virtual DbSet<champion> champion { get; set; }
        public virtual DbSet<item> item { get; set; }
        public virtual DbSet<mastery> mastery { get; set; }
        public virtual DbSet<rune> rune { get; set; }
        public virtual DbSet<spell> spell { get; set; }
        public virtual DbSet<whishlist> whishlist { get; set; }
    }
}
