//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoLWay.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class whishlist
    {
        public int id { get; set; }
        public string userId { get; set; }
        public int championId { get; set; }
        [Range(0, 1)]
        public int owned { get; set; }
        [Range(0, 10)]
        public long rank { get; set; }
    
        public virtual champion champion { get; set; }
        public virtual aspnetusers aspnetusers { get; set; }
    }
}
